- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew
    - homebrew-cask
    - ruby-build
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:

    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - ansible
      - heroku-toolbelt
      - peco
      - nvm
      - zsh-syntax-highlighting
      - packer
      - ack
      - autoconf
      - cmake
      - gdbm
      - libevent
      - pkg-config
      - colordiff
      - libyaml
      - protobuf
      - sqlite
      - tree
      - mobile-shell
      - pcre
      - readline
      - coreutils
      - graphviz
      - bdw-gc
      - libpng
      - xz
      - tmux
      - vim
      - jq
      - curl
      - wget
      - httpie
      - w3m
      - git
      - git-flow
      - tig
      - hub
      - git-extras
      - hg
      - rbenv
      - ruby
      - ruby-build
      - rbenv-gemset
      - rbenv-gem-rehash
      - pyenv-virtualenv
      - mysql
      - go
      - boot2docker
      - docker
      - mongodb
      - ctags
      - fontforge
      - gibo
      - zsh
      - zsh-completions
      - the_silver_searcher
      - dnsmasq
      - nodebrew
      - docker
      - boot2docker
      - terraform

    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - virtualbox
      - vagrant
      - vagrant-manager
      - iterm2
      - java
      - google-chrome
      - firefox
      - dropbox
      - kobito
      - gyazo
      - mysqlworkbench
      - sequel-pro
      - intellij-idea
      - appcode
      - quicklook-json
      - shiftit
      - alfred
      - evernote
      - slack
      - hipchat
      - skype
      - sqwiggle
      - mou
      - keepassx
      - marked
      - bathyscaphe
      - limechat
      - visualvm
      - yorufukurou
      - tunnelblick
      - google-japanese-ime
      - rubymine
      - heroku-toolbelt
      - charles

